### PR TITLE
Add TypeAlpine

### PR DESCRIPTION
**Pull request by noqcks**
apk is now in the purl spec: https://github.com/package-url/purl-spec/blob/master/PURL-TYPES.rst#apk

### CODE REVIEW

**Comment by noqcks** [comment]
@spiffcs ran gofmt and verified tests pass locally. you can run the workflow again

**Comment by kzantow** [comment]
@noqcks running this branch locally, I'm seeing the same test failures when running `make test`, but they sure don't look related to your change. I'll see if I can figure out what's going on here

**Comment by kzantow** [comment]
It looks like the problem is downloading updated test data. `make test` has:
```
curl -L https://raw.githubusercontent.com/package-url/purl-spec/master/test-suite-data.json -o testdata/test-suite-data.json
```
Ironically, there was a PR that adds this test data file in, which was merged: https://github.com/package-url/packageurl-go/pull/32 but it _still_ downloads the file when running `make test`.

**Comment by noqcks** [comment]
@kzantow this should fix it https://github.com/anchore/packageurl-go/pull/10

**Comment by kzantow** [comment]
@noqcks merged! I really would like to get our changes upstream, but this is good for moving forward quickly 👍

**Comment by noqcks** [comment]
Added upstream PRs:
- https://github.com/package-url/packageurl-go/pull/36
- https://github.com/package-url/packageurl-go/pull/38
- https://github.com/package-url/packageurl-go/pull/40

**Comment by noqcks** [comment]
tests seem to be failing now because it's running the job from the master branch (and still downloading the test data), and not the changed job on my PR.

**Comment by kzantow** [comment]
Main (master) branch is failing, too... I'm trying to sort through it.

**Comment by noqcks** [comment]
https://github.com/anchore/packageurl-go/pull/11

**Comment by kzantow** [comment]
Also merged 🎉

**Review by kzantow — APPROVED** [review]
Thanks for all your work on this contribution!

**Pull request merged**
